name: Self Lint
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    uses: validatedpatterns/github-actions-library/.github/workflows/superlinter.yml@v1
    with:
      runner: ubuntu-22.04
      sl_env: |
        VALIDATE_ALL_CODEBASE=false
        VALIDATE_NATURAL_LANGUAGE=false
